#cloud-config
hostname: cliente
users:
  - name: clientuser
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAr... # tu clave pública aquí
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

packages:
  - vim
  - curl
  - wget

runcmd:
  - echo "Client setup complete!" > /home/clientuser/setup.log
  - systemctl start some-service # Reemplaza con el servicio real si es necesario

final_message: "The client instance is ready!"